
const EMPTY_FIELDS_ERROR = 2000
const USER_NOT_FOUND_ERROR = 2001
const WRONG_EMAIL_OR_PASSWORD_ERROR = 2002
const INTERNAL_ERROR = 1000


module.exports={EMPTY_FIELDS_ERROR,USER_NOT_FOUND_ERROR,WRONG_EMAIL_OR_PASSWORD_ERROR,INTERNAL_ERROR};