POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "ghouas",
    "password": "password"
}

###
POST  http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "banoune",
    "password": "password"
}

###
GET http://localhost:3000/user/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZ2hvdWFzIiwidXNlcklkIjoiNjJkYWRmNTBmYWQ4MWYzZGQ4YmIyMjFiIn0sImlhdCI6MTY1ODYxMDY5NiwiZXhwIjoxNjU4Njk3MDk2fQ.ar8K1PWu-tRl4v5UOvGts3-LO65JyYS64q1a2PUZTW8

###
POST  http://localhost:3000/user/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZ2hvdWFzIiwidXNlcklkIjoiNjJkYWRmNTBmYWQ4MWYzZGQ4YmIyMjFiIn0sImlhdCI6MTY1ODUyMTQzMiwiZXhwIjoxNjU4NjA3ODMyfQ.cZEvQf1RgihD99TnY76WzjZHZiaQdJElqiz7gWaBcTA


  {  
  }

###
POST https://slack.com/api/oauth.v2.access&code=1234&client_id=3746919800806.3780629757872&client_secret=6661d9bec1baa27990d2b2ac3aacc742
Content-Type: application/x-www-form-urlencoded

###
POST  http://localhost:3000/slack/authorization
Content-Type: application/json

{
  "code":1253
}

###
GET  http://localhost:3000/ 
