POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "ghouas.abdelhak@gmail.com",
    "password": "password"
}

###
POST  http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "ghouas",
    "password": "password"
}

###
GET http://localhost:3000/user/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZ2hvdWFzIiwidXNlcklkIjoiNjJkYWRmNTBmYWQ4MWYzZGQ4YmIyMjFiIn0sImlhdCI6MTY1ODYxMDY5NiwiZXhwIjoxNjU4Njk3MDk2fQ.ar8K1PWu-tRl4v5UOvGts3-LO65JyYS64q1a2PUZTW8

###
POST  http://localhost:3000/user/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZ2hvdWFzIiwidXNlcklkIjoiNjJlMTg0MjE1MmVjYjk0YTBjYzA5Y2U1In0sImlhdCI6MTY1ODk0NzIwMCwiZXhwIjoxNjU5MDMzNjAwfQ.VxiERaljJ0bcI5GiGWOrlXdtz-HlCz0m1SDrLCmvKxo


  {
    "post":{
      "title":"ceci est mon premier post",
      "content":" ceci est le contenur de mon supposé premier post"
    }  
  }

###
POST https://slack.com/api/oauth.v2.access&code=1234&client_id=3746919800806.3780629757872&client_secret=6661d9bec1baa27990d2b2ac3aacc742
Content-Type: application/x-www-form-urlencoded

###
POST  http://localhost:3000/slack/authorization?code=3746919800806.4038037985714.6e75f866af0ee984d1ee43bdc011652161ba825a97af4d21d2e0462fe716d135&state=63163dfd825ee4782185a560 HTTP/1.1
Content-Type: application/x-www-form-urlencoded




###
GET  http://localhost:3000/ 

###
GET https://slack.com/api/conversations.list -H "Authorization: Bearer xoxb-3746919800806-3961811943894-cIKrRwVbDw4LlM81JzPtPznQ"

###
GET  http://localhost:3000/slack/slack_access_token
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZ2hvdWFzLmFiZGVsaGFrQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYyZTE4NDIxNTJlY2I5NGEwY2MwOWNlNSJ9LCJpYXQiOjE2NjIxNTIxOTUsImV4cCI6MTY2MjIzODU5NX0.YAHxHTJTga8DCW3l5i44uGLeeU1EelonZklSZnj7HaY

###
GET http://localhost:3000/mobile/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZ2hvdWFzLmFiZGVsaGFrQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYzMWM4ZGQxNzUxOGQwZWVjZjYwZjQ5NyJ9LCJpYXQiOjE2NjMzNjE5MTQsImV4cCI6MTY2MzQ0ODMxNH0.gOFq3OfEciow9cyMHurPPHwEP8nTts6hJrSNnpdR8nQ
###
POST http://localhost:3000/mobile/login
Content-Type: application/json

{
    "email": "ghouas.abdelhak@gmail.com",
    "password": "password"
}